// <auto-generated />
using System;
using AdvLab_WebApi.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdvLab_WebApi.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20240210060000_updatetablechangeLocation1")]
    partial class updatetablechangeLocation1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdvLab_WebApi.Models.AccessRight", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Assigning")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpID")
                        .HasColumnType("int");

                    b.Property<int?>("SOR")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AccessRights");
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.AddConnLab", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocCate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocID")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AddConnLabs");

                    b.HasData(
                        new
                        {
                            ID = 5,
                            LocActive = "No",
                            LocCate = "MAIN-LAB",
                            LocID = 1,
                            Location = "MAIN-LAB",
                            RegDate = new DateTime(2019, 3, 25, 11, 43, 59, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.AddDepart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SID")
                        .HasColumnType("int");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AddDeparts");

                    b.HasData(
                        new
                        {
                            ID = 116,
                            Depart = "Gynee",
                            Placement = "IPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 28, 58, 0, DateTimeKind.Unspecified),
                            SID = 77
                        },
                        new
                        {
                            ID = 117,
                            Depart = "NICU",
                            Placement = "IPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 46, 16, 0, DateTimeKind.Unspecified),
                            SID = 78
                        },
                        new
                        {
                            ID = 34,
                            Depart = "ALL",
                            Location = "GB",
                            Placement = "IT",
                            RegDate = new DateTime(2020, 1, 13, 22, 25, 6, 0, DateTimeKind.Unspecified),
                            SID = 15
                        },
                        new
                        {
                            ID = 77,
                            Depart = "IT",
                            Location = "GB",
                            Placement = "IT",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 46
                        },
                        new
                        {
                            ID = 114,
                            Depart = "Consultancy",
                            Placement = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 21, 44, 0, DateTimeKind.Unspecified),
                            SID = 75
                        },
                        new
                        {
                            ID = 115,
                            Depart = "RMO",
                            Placement = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 21, 44, 0, DateTimeKind.Unspecified),
                            SID = 76
                        },
                        new
                        {
                            ID = 119,
                            Depart = "Services",
                            Location = "GB",
                            Placement = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 21, 44, 0, DateTimeKind.Unspecified),
                            SID = 80
                        },
                        new
                        {
                            ID = 118,
                            Depart = "Ultrasound",
                            Placement = "OPD",
                            RegDate = new DateTime(2022, 1, 13, 13, 53, 56, 0, DateTimeKind.Unspecified),
                            SID = 79
                        },
                        new
                        {
                            ID = 1,
                            Depart = "BIOCHEMISTRY",
                            Location = "GB",
                            Placement = "PATH",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 1
                        },
                        new
                        {
                            ID = 2,
                            Depart = "BLOOD BANK",
                            Location = "GB",
                            Placement = "PATH",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 2
                        },
                        new
                        {
                            ID = 49,
                            Depart = "HEMATOLOGY",
                            Location = "GB",
                            Placement = "PATH",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 30
                        },
                        new
                        {
                            ID = 3,
                            Depart = "HISTOPATHOLOGY",
                            Location = "GB",
                            Placement = "PATH",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 3
                        },
                        new
                        {
                            ID = 4,
                            Depart = "MICROBIOLOGY",
                            Location = "GB",
                            Placement = "PATH",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 4
                        },
                        new
                        {
                            ID = 5,
                            Depart = "MOLECULAR PATHOLOGY",
                            Location = "GB",
                            Placement = "PATH",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 5
                        },
                        new
                        {
                            ID = 7,
                            Depart = "CT SCAN",
                            Location = "GB",
                            Placement = "RAD",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 7
                        },
                        new
                        {
                            ID = 8,
                            Depart = "ECG",
                            Location = "GB",
                            Placement = "RAD",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 8
                        },
                        new
                        {
                            ID = 10,
                            Depart = "ECHO",
                            Location = "GB",
                            Placement = "RAD",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 10
                        },
                        new
                        {
                            ID = 11,
                            Depart = "MRI",
                            Location = "GB",
                            Placement = "RAD",
                            RegDate = new DateTime(2018, 4, 20, 3, 7, 29, 0, DateTimeKind.Unspecified),
                            SID = 11
                        },
                        new
                        {
                            ID = 31,
                            Depart = "ULTRASOUND",
                            Location = "GB",
                            Placement = "RAD",
                            RegDate = new DateTime(2018, 4, 15, 2, 42, 2, 233, DateTimeKind.Unspecified),
                            SID = 13
                        },
                        new
                        {
                            ID = 32,
                            Depart = "X-RAY",
                            Location = "GB",
                            Placement = "RAD",
                            RegDate = new DateTime(2018, 4, 15, 2, 42, 2, 233, DateTimeKind.Unspecified),
                            SID = 14
                        });
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.AddDesignation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SID")
                        .HasColumnType("int");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AddDesignations");

                    b.HasData(
                        new
                        {
                            ID = 132,
                            Designation = "IT Trainee",
                            SID = 29
                        },
                        new
                        {
                            ID = 201,
                            Designation = "Accountant",
                            SID = 98
                        },
                        new
                        {
                            ID = 150,
                            Designation = "Administrator",
                            SID = 47
                        },
                        new
                        {
                            ID = 140,
                            Designation = "Assistant Branch Manager",
                            SID = 37
                        },
                        new
                        {
                            ID = 167,
                            Designation = "Assistant Lab Technician",
                            SID = 64
                        },
                        new
                        {
                            ID = 153,
                            Designation = "Assistant Technician",
                            SID = 50
                        },
                        new
                        {
                            ID = 119,
                            Designation = "Billing Incharge",
                            SID = 16
                        },
                        new
                        {
                            ID = 179,
                            Designation = "Branch Manager",
                            SID = 76
                        },
                        new
                        {
                            ID = 144,
                            Designation = "Business Development Executive",
                            SID = 41
                        },
                        new
                        {
                            ID = 138,
                            Designation = "Business Development Manager",
                            SID = 35
                        },
                        new
                        {
                            ID = 137,
                            Designation = "Business Development Officer",
                            SID = 34
                        },
                        new
                        {
                            ID = 146,
                            Designation = "Core Graphic Designer",
                            SID = 43
                        },
                        new
                        {
                            ID = 143,
                            Designation = "Corporate Sales Executive",
                            SID = 40
                        },
                        new
                        {
                            ID = 142,
                            Designation = "Corporate Sales Head",
                            SID = 39
                        },
                        new
                        {
                            ID = 198,
                            Designation = "Critical Care Technician",
                            SID = 95
                        },
                        new
                        {
                            ID = 157,
                            Designation = "Customer Service Executive",
                            SID = 54
                        },
                        new
                        {
                            ID = 148,
                            Designation = "Digital Media Coordinator",
                            SID = 45
                        },
                        new
                        {
                            ID = 147,
                            Designation = "Digital Media Designer",
                            SID = 44
                        },
                        new
                        {
                            ID = 176,
                            Designation = "Dispatch Coordinator",
                            SID = 73
                        },
                        new
                        {
                            ID = 178,
                            Designation = "Dispatch Officer",
                            SID = 75
                        },
                        new
                        {
                            ID = 174,
                            Designation = "Fleet Manager",
                            SID = 71
                        },
                        new
                        {
                            ID = 149,
                            Designation = "Graphic Designer",
                            SID = 46
                        },
                        new
                        {
                            ID = 121,
                            Designation = "Head Of Department",
                            SID = 18
                        },
                        new
                        {
                            ID = 197,
                            Designation = "Head Of Nurse",
                            SID = 94
                        },
                        new
                        {
                            ID = 159,
                            Designation = "Incharge",
                            SID = 56
                        },
                        new
                        {
                            ID = 127,
                            Designation = "IT Executive",
                            SID = 24
                        },
                        new
                        {
                            ID = 126,
                            Designation = "IT Incharge",
                            SID = 23
                        },
                        new
                        {
                            ID = 128,
                            Designation = "IT Officer",
                            SID = 25
                        },
                        new
                        {
                            ID = 130,
                            Designation = "IT Support Officer",
                            SID = 27
                        },
                        new
                        {
                            ID = 172,
                            Designation = "Janitorial Coordinator",
                            SID = 69
                        },
                        new
                        {
                            ID = 161,
                            Designation = "Junior Lab Technologist",
                            SID = 58
                        },
                        new
                        {
                            ID = 200,
                            Designation = "Junior Software Developer",
                            SID = 97
                        },
                        new
                        {
                            ID = 164,
                            Designation = "Lab Incharge",
                            SID = 61
                        },
                        new
                        {
                            ID = 162,
                            Designation = "Lab Manager",
                            SID = 59
                        },
                        new
                        {
                            ID = 163,
                            Designation = "Lab Supervisior",
                            SID = 60
                        },
                        new
                        {
                            ID = 154,
                            Designation = "Lab Technician",
                            SID = 51
                        },
                        new
                        {
                            ID = 160,
                            Designation = "Lab Technologist",
                            SID = 57
                        },
                        new
                        {
                            ID = 133,
                            Designation = "Lab Trainee",
                            SID = 30
                        },
                        new
                        {
                            ID = 131,
                            Designation = "Manager Infrastructure",
                            SID = 28
                        },
                        new
                        {
                            ID = 145,
                            Designation = "Marketing Manager",
                            SID = 42
                        },
                        new
                        {
                            ID = 196,
                            Designation = "Medical Officer",
                            SID = 93
                        },
                        new
                        {
                            ID = 170,
                            Designation = "Office Boy",
                            SID = 67
                        },
                        new
                        {
                            ID = 192,
                            Designation = "Phelbotomist",
                            SID = 89
                        },
                        new
                        {
                            ID = 151,
                            Designation = "Phlebotomist",
                            SID = 48
                        },
                        new
                        {
                            ID = 120,
                            Designation = "QC Manager /LAB Coordinator",
                            SID = 17
                        },
                        new
                        {
                            ID = 189,
                            Designation = "Receptionist",
                            SID = 86
                        },
                        new
                        {
                            ID = 155,
                            Designation = "Receptionist+Phlebotomist",
                            SID = 52
                        },
                        new
                        {
                            ID = 191,
                            Designation = "Recptionist/ Phelbotomist",
                            SID = 88
                        },
                        new
                        {
                            ID = 135,
                            Designation = "Regional Head Of Operations",
                            SID = 32
                        },
                        new
                        {
                            ID = 136,
                            Designation = "Regional Sales Manager",
                            SID = 33
                        },
                        new
                        {
                            ID = 177,
                            Designation = "Rider",
                            SID = 74
                        },
                        new
                        {
                            ID = 169,
                            Designation = "Senior Office Boy",
                            SID = 66
                        },
                        new
                        {
                            ID = 152,
                            Designation = "Senior Phlebotomist",
                            SID = 49
                        },
                        new
                        {
                            ID = 199,
                            Designation = "Senior Software Developer",
                            SID = 96
                        },
                        new
                        {
                            ID = 165,
                            Designation = "Senior Technician",
                            SID = 62
                        },
                        new
                        {
                            ID = 168,
                            Designation = "Senior Technologist",
                            SID = 65
                        },
                        new
                        {
                            ID = 129,
                            Designation = "Software Developers",
                            SID = 26
                        },
                        new
                        {
                            ID = 183,
                            Designation = "Sonologist",
                            SID = 80
                        },
                        new
                        {
                            ID = 190,
                            Designation = "Staff Nurse",
                            SID = 87
                        },
                        new
                        {
                            ID = 124,
                            Designation = "Store Incharge",
                            SID = 21
                        },
                        new
                        {
                            ID = 123,
                            Designation = "Store Officer",
                            SID = 20
                        },
                        new
                        {
                            ID = 122,
                            Designation = "Supply Chain Officer",
                            SID = 19
                        },
                        new
                        {
                            ID = 171,
                            Designation = "Sweeper",
                            SID = 68
                        },
                        new
                        {
                            ID = 156,
                            Designation = "Team Leader",
                            SID = 53
                        },
                        new
                        {
                            ID = 181,
                            Designation = "Technician",
                            SID = 78
                        },
                        new
                        {
                            ID = 166,
                            Designation = "Technologist",
                            SID = 63
                        },
                        new
                        {
                            ID = 125,
                            Designation = "Trainee",
                            SID = 22
                        },
                        new
                        {
                            ID = 139,
                            Designation = "Trainee",
                            SID = 36
                        },
                        new
                        {
                            ID = 188,
                            Designation = "Trainee Assistant",
                            SID = 85
                        },
                        new
                        {
                            ID = 118,
                            Designation = "Trainee Finance",
                            SID = 15
                        },
                        new
                        {
                            ID = 184,
                            Designation = "Ultrasound Coordinator",
                            SID = 81
                        },
                        new
                        {
                            ID = 180,
                            Designation = "X-Ray Technician",
                            SID = 77
                        },
                        new
                        {
                            ID = 223,
                            Designation = "Accounts & Finance Executive",
                            SID = 120
                        },
                        new
                        {
                            ID = 214,
                            Designation = "Accounts Assistant / Computer Operator",
                            SID = 111
                        },
                        new
                        {
                            ID = 104,
                            Designation = "Advisor to The Board",
                            SID = 1
                        },
                        new
                        {
                            ID = 217,
                            Designation = "Aesthetic Treatment Technician",
                            SID = 114
                        },
                        new
                        {
                            ID = 230,
                            Designation = "Area Sales Manager",
                            SID = 127
                        },
                        new
                        {
                            ID = 239,
                            Designation = "Assiatant HR & Finance",
                            SID = 136
                        },
                        new
                        {
                            ID = 111,
                            Designation = "Assistant Manager HR/Admin",
                            SID = 8
                        },
                        new
                        {
                            ID = 187,
                            Designation = "Assistant Technician",
                            SID = 84
                        },
                        new
                        {
                            ID = 235,
                            Designation = "BDO",
                            SID = 132
                        },
                        new
                        {
                            ID = 116,
                            Designation = "Billing Executive",
                            SID = 13
                        },
                        new
                        {
                            ID = 241,
                            Designation = "Billing/Recovery Incharge",
                            SID = 138
                        },
                        new
                        {
                            ID = 234,
                            Designation = "Branch Manager + Marketing",
                            SID = 131
                        },
                        new
                        {
                            ID = 227,
                            Designation = "Branch Supervisor",
                            SID = 124
                        },
                        new
                        {
                            ID = 236,
                            Designation = "Business Develpment Manager",
                            SID = 133
                        },
                        new
                        {
                            ID = 107,
                            Designation = "Chief Executive Officer",
                            SID = 4
                        },
                        new
                        {
                            ID = 113,
                            Designation = "Chief Financial Officer",
                            SID = 10
                        },
                        new
                        {
                            ID = 204,
                            Designation = "Chief Pathologist",
                            SID = 101
                        },
                        new
                        {
                            ID = 109,
                            Designation = "Consultant",
                            SID = 6
                        },
                        new
                        {
                            ID = 218,
                            Designation = "Corporate Officer",
                            SID = 115
                        },
                        new
                        {
                            ID = 216,
                            Designation = "CS Lead",
                            SID = 113
                        },
                        new
                        {
                            ID = 222,
                            Designation = "CSR TEAM LEAD",
                            SID = 119
                        },
                        new
                        {
                            ID = 244,
                            Designation = "Customer Service Team Leader",
                            SID = 141
                        },
                        new
                        {
                            ID = 209,
                            Designation = "Data Entry Operater",
                            SID = 106
                        },
                        new
                        {
                            ID = 158,
                            Designation = "Data Entry Operator",
                            SID = 55
                        },
                        new
                        {
                            ID = 173,
                            Designation = "Driver",
                            SID = 70
                        },
                        new
                        {
                            ID = 210,
                            Designation = "Electrician",
                            SID = 107
                        },
                        new
                        {
                            ID = 240,
                            Designation = "Finance Executive",
                            SID = 137
                        },
                        new
                        {
                            ID = 114,
                            Designation = "Finance Manager",
                            SID = 11
                        },
                        new
                        {
                            ID = 117,
                            Designation = "Finance Trainee",
                            SID = 14
                        },
                        new
                        {
                            ID = 245,
                            Designation = "Front Desk Officer",
                            SID = 142
                        },
                        new
                        {
                            ID = 243,
                            Designation = "Head of Customer Relation",
                            SID = 140
                        },
                        new
                        {
                            ID = 110,
                            Designation = "Head Of HR / Admin",
                            SID = 7
                        },
                        new
                        {
                            ID = 108,
                            Designation = "Head Of PCR Department",
                            SID = 5
                        },
                        new
                        {
                            ID = 203,
                            Designation = "HR Assistant",
                            SID = 100
                        },
                        new
                        {
                            ID = 112,
                            Designation = "HR Executive",
                            SID = 9
                        },
                        new
                        {
                            ID = 238,
                            Designation = "HR Intern",
                            SID = 135
                        },
                        new
                        {
                            ID = 242,
                            Designation = "Internal Audit Executive",
                            SID = 139
                        },
                        new
                        {
                            ID = 221,
                            Designation = "Junior Technologist",
                            SID = 118
                        },
                        new
                        {
                            ID = 105,
                            Designation = "Laboratory Director",
                            SID = 2
                        },
                        new
                        {
                            ID = 246,
                            Designation = "Laboratory Incharge",
                            SID = 143
                        },
                        new
                        {
                            ID = 205,
                            Designation = "Labortory Manager",
                            SID = 102
                        },
                        new
                        {
                            ID = 219,
                            Designation = "Maintenance + Office Boy",
                            SID = 116
                        },
                        new
                        {
                            ID = 233,
                            Designation = "Marketing Coordinator",
                            SID = 130
                        },
                        new
                        {
                            ID = 225,
                            Designation = "Medical Consultant",
                            SID = 122
                        },
                        new
                        {
                            ID = 194,
                            Designation = "Medical Officer",
                            SID = 91
                        },
                        new
                        {
                            ID = 220,
                            Designation = "Micro Biologist",
                            SID = 117
                        },
                        new
                        {
                            ID = 232,
                            Designation = "Molecular Lab Technologist",
                            SID = 129
                        },
                        new
                        {
                            ID = 134,
                            Designation = "Network & Telecom Technician",
                            SID = 31
                        },
                        new
                        {
                            ID = 212,
                            Designation = "Nurse",
                            SID = 109
                        },
                        new
                        {
                            ID = 175,
                            Designation = "Office Assistant",
                            SID = 72
                        },
                        new
                        {
                            ID = 106,
                            Designation = "Pathologist",
                            SID = 3
                        },
                        new
                        {
                            ID = 206,
                            Designation = "Pathologist",
                            SID = 103
                        },
                        new
                        {
                            ID = 237,
                            Designation = "Pharmacy Incharge",
                            SID = 134
                        },
                        new
                        {
                            ID = 224,
                            Designation = "Phlebotomist + Rider",
                            SID = 121
                        },
                        new
                        {
                            ID = 247,
                            Designation = "Procurement Executive",
                            SID = 144
                        },
                        new
                        {
                            ID = 228,
                            Designation = "Radiologist",
                            SID = 125
                        },
                        new
                        {
                            ID = 229,
                            Designation = "Regional Head Interior",
                            SID = 126
                        },
                        new
                        {
                            ID = 211,
                            Designation = "Regional Head- Corporate Sales",
                            SID = 108
                        },
                        new
                        {
                            ID = 141,
                            Designation = "Regional Sales Manager Retail",
                            SID = 38
                        },
                        new
                        {
                            ID = 115,
                            Designation = "Senior Finance Executive",
                            SID = 12
                        },
                        new
                        {
                            ID = 226,
                            Designation = "SMO",
                            SID = 123
                        },
                        new
                        {
                            ID = 231,
                            Designation = "Sr. BDO",
                            SID = 128
                        },
                        new
                        {
                            ID = 213,
                            Designation = "Technical Incharge",
                            SID = 110
                        },
                        new
                        {
                            ID = 215,
                            Designation = "Technologist",
                            SID = 112
                        },
                        new
                        {
                            ID = 207,
                            Designation = "Trainee Molecular Technologist",
                            SID = 104
                        },
                        new
                        {
                            ID = 208,
                            Designation = "Vaccinator",
                            SID = 105
                        });
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.AddLocation", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompMac")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocActive")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocCate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocID")
                        .HasColumnType("int");

                    b.Property<int?>("LocSno")
                        .HasColumnType("int");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reconsile")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AddLocations");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompMac = "FB: Address Contact",
                            Idloc = "NKM",
                            LocActive = "No",
                            LocCate = "Main",
                            LocID = 10150121,
                            LocSno = 0,
                            Location = "Main",
                            Reconsile = "Active",
                            RegDate = new DateTime(2018, 5, 1, 1, 50, 40, 0, DateTimeKind.Unspecified),
                            UId = 1
                        });
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.AddPlacement", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SID")
                        .HasColumnType("int");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AddPlacements");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "PATH",
                            PlaceName = "Pathology",
                            RegDate = new DateTime(2018, 4, 15, 3, 21, 16, 0, DateTimeKind.Unspecified),
                            SID = 1,
                            UId = 1
                        },
                        new
                        {
                            ID = 2,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "RAD",
                            PlaceName = "Radiology",
                            RegDate = new DateTime(2018, 4, 15, 3, 21, 16, 0, DateTimeKind.Unspecified),
                            SID = 2,
                            UId = 2
                        },
                        new
                        {
                            ID = 3,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "OPD",
                            PlaceName = "Outpatient Department",
                            RegDate = new DateTime(2020, 1, 18, 1, 15, 27, 0, DateTimeKind.Unspecified),
                            SID = 3,
                            UId = 3
                        },
                        new
                        {
                            ID = 4,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "CSR",
                            PlaceName = "Customer Service Representative",
                            RegDate = new DateTime(2018, 4, 15, 3, 21, 16, 0, DateTimeKind.Unspecified),
                            SID = 4,
                            UId = 4
                        },
                        new
                        {
                            ID = 5,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "IT",
                            PlaceName = "Information Technology",
                            RegDate = new DateTime(2021, 2, 28, 12, 10, 7, 0, DateTimeKind.Unspecified),
                            SID = 5,
                            UId = 5
                        },
                        new
                        {
                            ID = 6,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "HR",
                            PlaceName = "Human Resources",
                            RegDate = new DateTime(2018, 4, 15, 3, 21, 16, 0, DateTimeKind.Unspecified),
                            SID = 6,
                            UId = 6
                        },
                        new
                        {
                            ID = 7,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "IPD",
                            PlaceName = "Inpatient Department",
                            RegDate = new DateTime(2018, 4, 15, 3, 21, 16, 0, DateTimeKind.Unspecified),
                            SID = 7,
                            UId = 7
                        },
                        new
                        {
                            ID = 8,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "FIN",
                            PlaceName = "Finance",
                            RegDate = new DateTime(2018, 4, 15, 3, 21, 16, 0, DateTimeKind.Unspecified),
                            SID = 8,
                            UId = 8
                        },
                        new
                        {
                            ID = 9,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "MKTG",
                            PlaceName = "Marketing",
                            RegDate = new DateTime(2018, 4, 15, 3, 21, 16, 0, DateTimeKind.Unspecified),
                            SID = 9,
                            UId = 9
                        },
                        new
                        {
                            ID = 10,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "SCM",
                            PlaceName = "Supply Chain Management",
                            RegDate = new DateTime(2018, 4, 15, 3, 21, 16, 0, DateTimeKind.Unspecified),
                            SID = 9,
                            UId = 9
                        },
                        new
                        {
                            ID = 11,
                            CompMac = "Null",
                            Idloc = "Null",
                            PlaceCode = "MED",
                            PlaceName = "Medical"
                        });
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.AddSubDepart", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("SID")
                        .HasColumnType("int");

                    b.Property<string>("SubDepart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AddSubDeparts");

                    b.HasData(
                        new
                        {
                            ID = 121,
                            Depart = "Gynee",
                            Location = "IPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 41, 43, 0, DateTimeKind.Unspecified),
                            SID = 7,
                            SubDepart = "Labour Room"
                        },
                        new
                        {
                            ID = 120,
                            Depart = "Gynee",
                            Location = "IPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 34, 19, 0, DateTimeKind.Unspecified),
                            SID = 6,
                            SubDepart = "Operation"
                        },
                        new
                        {
                            ID = 123,
                            Depart = "NICU",
                            Location = "IPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 46, 33, 0, DateTimeKind.Unspecified),
                            SID = 9,
                            SubDepart = "Admission"
                        },
                        new
                        {
                            ID = 122,
                            Depart = "NICU",
                            Location = "IPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 46, 33, 0, DateTimeKind.Unspecified),
                            SID = 8,
                            SubDepart = "Observation"
                        },
                        new
                        {
                            ID = 40,
                            Depart = "IT",
                            Location = "IT",
                            RegDate = new DateTime(2021, 5, 11, 12, 31, 38, 0, DateTimeKind.Unspecified),
                            SID = 37,
                            SubDepart = "Governance"
                        },
                        new
                        {
                            ID = 31,
                            Depart = "IT",
                            Location = "IT",
                            RegDate = new DateTime(2021, 5, 11, 12, 31, 38, 0, DateTimeKind.Unspecified),
                            SID = 29,
                            SubDepart = "Infrastructure Department"
                        },
                        new
                        {
                            ID = 29,
                            Depart = "IT",
                            Location = "IT",
                            RegDate = new DateTime(2021, 2, 2, 21, 15, 19, 0, DateTimeKind.Unspecified),
                            SID = 27,
                            SubDepart = "Operation and Maintenance"
                        },
                        new
                        {
                            ID = 72,
                            Depart = "IT",
                            Location = "IT",
                            RegDate = new DateTime(2021, 2, 2, 21, 15, 19, 0, DateTimeKind.Unspecified),
                            SID = 69,
                            SubDepart = "Software Development"
                        },
                        new
                        {
                            ID = 116,
                            Depart = "Consultancy",
                            Location = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 29, 48, 0, DateTimeKind.Unspecified),
                            SID = 2,
                            SubDepart = "Cardiology"
                        },
                        new
                        {
                            ID = 125,
                            Depart = "Consultancy",
                            Location = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 46, 33, 0, DateTimeKind.Unspecified),
                            SID = 11,
                            SubDepart = "Dentist"
                        },
                        new
                        {
                            ID = 115,
                            Depart = "Consultancy",
                            Location = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 29, 48, 0, DateTimeKind.Unspecified),
                            SID = 1,
                            SubDepart = "Diabetes"
                        },
                        new
                        {
                            ID = 117,
                            Depart = "Consultancy",
                            Location = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 29, 48, 0, DateTimeKind.Unspecified),
                            SID = 3,
                            SubDepart = "ENT"
                        },
                        new
                        {
                            ID = 126,
                            Depart = "Consultancy",
                            Location = "OPD",
                            RegDate = new DateTime(2022, 1, 15, 12, 51, 45, 0, DateTimeKind.Unspecified),
                            SID = 12,
                            SubDepart = "General"
                        },
                        new
                        {
                            ID = 124,
                            Depart = "Consultancy",
                            Location = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 46, 33, 0, DateTimeKind.Unspecified),
                            SID = 10,
                            SubDepart = "Gynecology"
                        },
                        new
                        {
                            ID = 118,
                            Depart = "RMO",
                            Location = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 29, 48, 0, DateTimeKind.Unspecified),
                            SID = 4,
                            SubDepart = "General"
                        },
                        new
                        {
                            ID = 119,
                            Depart = "Services",
                            Location = "OPD",
                            RegDate = new DateTime(2021, 12, 16, 4, 29, 48, 0, DateTimeKind.Unspecified),
                            SID = 5,
                            SubDepart = "Services"
                        },
                        new
                        {
                            ID = 79,
                            Depart = "Admin",
                            Location = "PATH",
                            RegDate = new DateTime(2021, 5, 10, 16, 13, 47, 0, DateTimeKind.Unspecified),
                            SID = 74,
                            SubDepart = "Transport"
                        },
                        new
                        {
                            ID = 2,
                            Depart = "BIOCHEMISTRY",
                            Location = "Path",
                            RegDate = new DateTime(2019, 7, 7, 16, 30, 43, 0, DateTimeKind.Unspecified),
                            SID = 2,
                            SubDepart = "ROUTINE CHEMISTRY"
                        },
                        new
                        {
                            ID = 1,
                            Depart = "BIOCHEMISTRY",
                            Location = "Path",
                            RegDate = new DateTime(2018, 4, 15, 2, 35, 57, 0, DateTimeKind.Unspecified),
                            SID = 1,
                            SubDepart = "SPECIAL CHEMISTRY"
                        },
                        new
                        {
                            ID = 24,
                            Depart = "BIOCHEMISTRY",
                            Location = "Path",
                            RegDate = new DateTime(2018, 4, 15, 2, 35, 57, 0, DateTimeKind.Unspecified),
                            SID = 22,
                            SubDepart = "SPECIAL CHEMISTRY / IMMUNOLOGY"
                        },
                        new
                        {
                            ID = 27,
                            Depart = "BIOCHEMISTRY",
                            Location = "Path",
                            RegDate = new DateTime(2018, 4, 15, 2, 35, 57, 0, DateTimeKind.Unspecified),
                            SID = 25,
                            SubDepart = "SPECIAL CHEMISTRY / IMMUNOLOGY / OUT SIDE"
                        },
                        new
                        {
                            ID = 25,
                            Depart = "BIOCHEMISTRY",
                            Location = "PATH",
                            RegDate = new DateTime(2018, 4, 15, 2, 35, 57, 0, DateTimeKind.Unspecified),
                            SID = 23,
                            SubDepart = "SPECIAL CHEMISTRY / OUT SIDE"
                        },
                        new
                        {
                            ID = 76,
                            Depart = "Distribution",
                            Location = "PATH",
                            RegDate = new DateTime(2021, 12, 27, 19, 39, 29, 0, DateTimeKind.Unspecified),
                            SID = 71,
                            SubDepart = "Bulk Dispatch"
                        },
                        new
                        {
                            ID = 75,
                            Depart = "Distribution",
                            Location = "PATH",
                            RegDate = new DateTime(2021, 12, 27, 19, 39, 29, 0, DateTimeKind.Unspecified),
                            SID = 70,
                            SubDepart = "Routine Dispatch"
                        },
                        new
                        {
                            ID = 28,
                            Depart = "HEMATOLOGY",
                            Location = "Path",
                            SID = 26,
                            SubDepart = "HEMATOLOGY"
                        },
                        new
                        {
                            ID = 26,
                            Depart = "HISTOPATHOLOGY",
                            Location = "PATH",
                            RegDate = new DateTime(2020, 7, 15, 0, 15, 1, 0, DateTimeKind.Unspecified),
                            SID = 24,
                            SubDepart = "CYTOLOGY"
                        },
                        new
                        {
                            ID = 4,
                            Depart = "HISTOPATHOLOGY",
                            Location = "Path",
                            SID = 4,
                            SubDepart = "HISTOPATHOLOGY"
                        },
                        new
                        {
                            ID = 5,
                            Depart = "MICROBIOLOGY",
                            Location = "Path",
                            SID = 5,
                            SubDepart = "BACTERIOLOGY"
                        },
                        new
                        {
                            ID = 18,
                            Depart = "MICROBIOLOGY",
                            Location = "Path",
                            SID = 16,
                            SubDepart = "Culture Sensitivity"
                        },
                        new
                        {
                            ID = 6,
                            Depart = "MICROBIOLOGY",
                            Location = "Path",
                            SID = 6,
                            SubDepart = "PARASITOLOGY"
                        },
                        new
                        {
                            ID = 7,
                            Depart = "MICROBIOLOGY",
                            Location = "Path",
                            SID = 7,
                            SubDepart = "SEROLOGY"
                        },
                        new
                        {
                            ID = 23,
                            Depart = "MOLECULAR PATHOLOGY",
                            Location = "Path",
                            SID = 21,
                            SubDepart = "BLOOD"
                        },
                        new
                        {
                            ID = 8,
                            Depart = "MOLECULAR PATHOLOGY",
                            Location = "Path",
                            SID = 8,
                            SubDepart = "MOLECULAR PATHOLOGY"
                        },
                        new
                        {
                            ID = 22,
                            Depart = "MOLECULAR PATHOLOGY",
                            Location = "Path",
                            SID = 20,
                            SubDepart = "NASAL"
                        },
                        new
                        {
                            ID = 11,
                            Depart = "COLOR DOPPLER",
                            Location = "Rad",
                            SID = 9,
                            SubDepart = "COLOR DOPPLER"
                        },
                        new
                        {
                            ID = 12,
                            Depart = "CT SCAN",
                            Location = "Rad",
                            SID = 10,
                            SubDepart = "CT SCAN"
                        },
                        new
                        {
                            ID = 35,
                            Depart = "Mancom",
                            Location = "Rad",
                            SID = 32,
                            SubDepart = "Mancom"
                        },
                        new
                        {
                            ID = 13,
                            Depart = "MRI",
                            Location = "Rad",
                            SID = 11,
                            SubDepart = "MRI"
                        },
                        new
                        {
                            ID = 71,
                            Depart = "PHYSIOLOGY",
                            Location = "Rad",
                            RegDate = new DateTime(2018, 4, 15, 2, 35, 57, 0, DateTimeKind.Unspecified),
                            SID = 68,
                            SubDepart = "PHYSIOLOGY"
                        },
                        new
                        {
                            ID = 34,
                            Depart = "Sonology",
                            Location = "Rad",
                            RegDate = new DateTime(2021, 5, 12, 14, 21, 14, 0, DateTimeKind.Unspecified),
                            SID = 32,
                            SubDepart = "Sonology"
                        },
                        new
                        {
                            ID = 16,
                            Depart = "ULTRASOUND",
                            Location = "Rad",
                            RegDate = new DateTime(2021, 12, 13, 19, 27, 7, 0, DateTimeKind.Unspecified),
                            SID = 14,
                            SubDepart = "ULTRASOUND"
                        },
                        new
                        {
                            ID = 17,
                            Depart = "X-RAY",
                            Location = "Rad",
                            RegDate = new DateTime(2021, 12, 13, 19, 27, 7, 0, DateTimeKind.Unspecified),
                            SID = 15,
                            SubDepart = "Xray"
                        });
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.CrystalReportPath", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("CNL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CrystalReport")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DefaultClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Loc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("db")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("server")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("CrystalReportPaths");

                    b.HasData(
                        new
                        {
                            id = 1,
                            CNL = "MAIN-LAB",
                            CrystalReport = "\\192.168.73.3\\ALAB Reports\\",
                            DefaultClient = "SELF",
                            Loc = "NKM",
                            Password = "M89.SolutioN",
                            UserName = "sa",
                            db = "AdvancedLab",
                            server = "AdvancedLab"
                        });
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.DescCashier", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BillNo")
                        .HasColumnType("int");

                    b.Property<double?>("BlanceA")
                        .HasColumnType("float");

                    b.Property<string>("CStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ClientID")
                        .HasColumnType("int");

                    b.Property<string>("ClientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comments")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConsName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreditCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CurrentB")
                        .HasColumnType("float");

                    b.Property<double?>("DiscPer")
                        .HasColumnType("float");

                    b.Property<double?>("Discount")
                        .HasColumnType("float");

                    b.Property<string>("DortocSMS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_VNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("GrossA")
                        .HasColumnType("float");

                    b.Property<string>("Idloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvNo")
                        .HasColumnType("int");

                    b.Property<string>("InvoiceSMS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LabNo")
                        .HasColumnType("int");

                    b.Property<int?>("MRNO")
                        .HasColumnType("int");

                    b.Property<double?>("PaidA")
                        .HasColumnType("float");

                    b.Property<string>("PaymentMode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Pwd")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RIdloc1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RUId1")
                        .HasColumnType("int");

                    b.Property<string>("RUname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RV1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("RbalanceA")
                        .HasColumnType("float");

                    b.Property<DateTime?>("RbalanceDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TaxN")
                        .HasColumnType("float");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("TotalA")
                        .HasColumnType("float");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.Property<string>("Uname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DescCashiers");
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.DescLab", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BarcodeNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNL")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Charges")
                        .HasColumnType("int");

                    b.Property<string>("CpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depart")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DescID")
                        .HasColumnType("int");

                    b.Property<string>("DescName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("InvNo")
                        .HasColumnType("int");

                    b.Property<int?>("LabNo")
                        .HasColumnType("int");

                    b.Property<int?>("MRNO")
                        .HasColumnType("int");

                    b.Property<string>("Placement")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RepDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ReportHeading")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StatusDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SubDepart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TestCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.Property<string>("Uname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DescLabs");
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.DescQ", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CpName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CpNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DescStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LocationNo")
                        .HasColumnType("int");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.Property<string>("Uname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DescQs");
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.DuesRecQ", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("ActionDate")
                        .HasColumnType("datetime2");

                    b.Property<double?>("AmountRec")
                        .HasColumnType("float");

                    b.Property<string>("Idloc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("LabNo")
                        .HasColumnType("int");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.Property<string>("Uname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("DuesRecQs");
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.LoginLog", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CompName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IP")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MacAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UserID")
                        .HasColumnType("int");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("logDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.PatReg", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Age")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AgeType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DBO")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Idloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Initial")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("MrNo")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("RelName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Relation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.Property<string>("Uname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("PatRegs");
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.Role", b =>
                {
                    b.Property<int>("RoleID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleID"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleID");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleID = 1,
                            RoleName = "Receptionist"
                        },
                        new
                        {
                            RoleID = 2,
                            RoleName = "Phlebotomist"
                        },
                        new
                        {
                            RoleID = 3,
                            RoleName = "Receptionist + Phlebotomist"
                        },
                        new
                        {
                            RoleID = 4,
                            RoleName = "Dispatcher"
                        },
                        new
                        {
                            RoleID = 5,
                            RoleName = "Medical Technologist"
                        },
                        new
                        {
                            RoleID = 6,
                            RoleName = "Lab Technician"
                        },
                        new
                        {
                            RoleID = 7,
                            RoleName = "Lab Manager"
                        },
                        new
                        {
                            RoleID = 8,
                            RoleName = "Branch Manager"
                        },
                        new
                        {
                            RoleID = 9,
                            RoleName = "Regional Manager"
                        },
                        new
                        {
                            RoleID = 10,
                            RoleName = "Pathologist"
                        },
                        new
                        {
                            RoleID = 11,
                            RoleName = "Human Resource"
                        },
                        new
                        {
                            RoleID = 12,
                            RoleName = "Accountant"
                        },
                        new
                        {
                            RoleID = 13,
                            RoleName = "Finance"
                        },
                        new
                        {
                            RoleID = 14,
                            RoleName = "General Manager"
                        },
                        new
                        {
                            RoleID = 15,
                            RoleName = "Administrator"
                        },
                        new
                        {
                            RoleID = 16,
                            RoleName = "CEO"
                        },
                        new
                        {
                            RoleID = 17,
                            RoleName = "Director"
                        });
                });

            modelBuilder.Entity("AdvLab_WebApi.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CNL")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClientV")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CompMac")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Depart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Designation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("EmpID")
                        .HasColumnType("int");

                    b.Property<string>("Idloc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginStatusComp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LoginStatusIP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NSend")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayGenerate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PlaceCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Placement")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("RegDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("RoleID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDepart")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Token")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UId")
                        .HasColumnType("int");

                    b.Property<string>("UName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CNL = "MAIN-LAB",
                            ClientV = "Main",
                            CompMac = "Null",
                            Depart = "All",
                            Designation = "IT",
                            EmpID = 1,
                            Idloc = "Main",
                            Location = "Main",
                            LoginStatus = "No",
                            LoginStatusComp = "Null",
                            LoginStatusIP = "Null",
                            NSend = "No",
                            PayGenerate = "No",
                            Place = "Null",
                            PlaceCategory = "Null",
                            Placement = "Path",
                            RoleID = 17,
                            Status = "Yes",
                            SubDepart = "All",
                            Token = "Null",
                            UName = "Admin",
                            UPassword = "admin@786"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
