using Microsoft.AspNetCore.Mvc.Abstractions;
using Microsoft.EntityFrameworkCore;

namespace AdvLab_WebApi.Models
{
    public class AppDBContext : DbContext
    {
        public AppDBContext(DbContextOptions<AppDBContext> options) : base(options)
        {
        }

        public DbSet<User> Users { get; set; }
        public virtual DbSet<LoginLog> LoginLogs { get; set; }
        public virtual DbSet<AddLocation> AddLocations { get; set; }
        public virtual DbSet<AddConnLab> AddConnLabs { get; set; }
        public virtual DbSet<AccessRight> AccessRights { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<AddDepart> AddDeparts { get; set; }
        public virtual DbSet<AddSubDepart> AddSubDeparts { get; set; }
        public virtual DbSet<AddPlacement> AddPlacements { get; set; }
        public virtual DbSet<AddDesignation> AddDesignations { get; set; }

        public virtual DbSet<CrystalReportPath> CrystalReportPaths { get; set; }
        public virtual DbSet<DescCashier> DescCashiers { get; set; }
        public virtual DbSet<DescLab> DescLabs { get; set; }
        public virtual DbSet<DescQ> DescQs { get; set; }
        public virtual DbSet<DuesRecQ> DuesRecQs { get; set; }
        public virtual DbSet<PatReg> PatRegs { get; set; }
        public virtual DbSet<PatReg_Shortkey> PatReg_Shortkeys { get; set; }
        public virtual DbSet<AddClient> AddClients { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<CrystalReportPath>().HasData(
            new CrystalReportPath()
            {
                id = 1,
                CrystalReport = "\\192.168.73.3\\ALAB Reports\\",
                UserName = "sa",
                Password = "M89.SolutioN",
                db = "AdvancedLab",
                server = "AdvancedLab",
                Loc = "Main",
                CNL = "MAIN-LAB",
                DefaultClient = "SELF"
            });
            modelBuilder.Entity<AddClient>().HasData(
    new AddClient()
    {
        ID = 1,
        RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), // Provide the appropriate default value
        CID = 1, // Provide the appropriate default value
        CName = "SELF",
        ComName = "SELF",
        ClientActive = "Active",
        PerA = "Yes",
        Pwd = "A123456",
        DescType = "Cash",
        PriceChangabletrue = "No",
        Location = "Main",
        CLocation = "Main",
        CCont = "",
        CEmail = "",
        Address = "",
        Inc_Routine = 0.0, // Provide the appropriate default value
        Inc_Special = 0.0,
        Inc_NoDisc = 0.0,
        Inc_Xray = 0.0,
        Inc_Ultra = 0.0,
        Inc_Ctscan = 0.0,
        Inc_Mri = 0.0,
        Inc_Echo = 0.0,
        Inc_Ecg = 0.0,
        Inc_Cdopler = 0.0,
        UId = 1, // Provide the appropriate default value
        BDO = 1, // Provide the appropriate default value
        BusinessType = "Walk-In",
        ClientInstraction = "",
        PAWC = "No",
        Dsc_Routine = 0.0, // Provide the appropriate default value
        Dsc_Special = 0.0,
        Dsc_NoDisc = 0.0,
        Dsc_Xray = 0.0,
        Dsc_Ultra = 0.0,
        Dsc_Ctscan = 0.0,
        Dsc_Mri = 0.0,
        Dsc_Echo = 0.0,
        Dsc_Ecg = 0.0,
        Dsc_Cdopler = 0.0
    }
);
            modelBuilder.Entity<PatReg_Shortkey>().HasData(
        new PatReg_Shortkey { Sno = 1, Initial = "MR", Relation = "S/O", Years = "YEARS", Gender = "MALE" },
        new PatReg_Shortkey { Sno = 2, Initial = "MRS", Relation = "W/O", Years = "YEARS", Gender = "FEMALE" },
        new PatReg_Shortkey { Sno = 3, Initial = "MISS", Relation = "D/O", Years = "YEARS", Gender = "FEMALE" },
        new PatReg_Shortkey { Sno = 4, Initial = "MASTER", Relation = "S/O", Years = "", Gender = "MALE" },
        new PatReg_Shortkey { Sno = 5, Initial = "BABY", Relation = "D/O", Years = "", Gender = "FEMALE" },
        new PatReg_Shortkey { Sno = 6, Initial = "MS", Relation = "D/O", Years = "", Gender = "FEMALE" },
        new PatReg_Shortkey { Sno = 7, Initial = "DR", Relation = "", Years = "", Gender = "" }
    );
            modelBuilder.Entity<User>().HasData(
                new User()
                {
                    ID = 1,
                    EmpID = 1,
                    UName = "Admin",
                    UPassword = "admin@786",
                    Status = "Yes",
                    CNL = "MAIN-LAB",
                    ClientV = "Main",
                    CompMac = "Null",
                    Depart = "All",
                    SubDepart = "All",
                    Placement = "Path",
                    Designation = "IT",
                    Idloc = "Main",
                    RoleID = 17,
                    Location = "Main",
                    LoginStatus = "No",
                    LoginStatusComp = "Null",
                    LoginStatusIP = "Null",
                    NSend = "No",
                    PayGenerate = "No",
                    Place = "Null",
                    PlaceCategory = "Null",
                    Token = "Null"
                });
            modelBuilder.Entity<Role>().HasData(
                    new Role { RoleID = 1, RoleName = "Receptionist" },
                    new Role { RoleID = 2, RoleName = "Phlebotomist" },
                    new Role { RoleID = 3, RoleName = "Receptionist + Phlebotomist" },
                    new Role { RoleID = 4, RoleName = "Dispatcher" },
                    new Role { RoleID = 5, RoleName = "Medical Technologist" },
                    new Role { RoleID = 6, RoleName = "Lab Technician" },
                    new Role { RoleID = 7, RoleName = "Lab Manager" },
                    new Role { RoleID = 8, RoleName = "Branch Manager" },
                    new Role { RoleID = 9, RoleName = "Regional Manager" },
                    new Role { RoleID = 10, RoleName = "Pathologist" },
                    new Role { RoleID = 11, RoleName = "Human Resource" },
                    new Role { RoleID = 12, RoleName = "Accountant" },
                    new Role { RoleID = 13, RoleName = "Finance" },
                    new Role { RoleID = 14, RoleName = "General Manager" },
                    new Role { RoleID = 15, RoleName = "Administrator" },
                    new Role { RoleID = 16, RoleName = "CEO" },
                    new Role { RoleID = 17, RoleName = "Director" }
                );
            modelBuilder.Entity<AddPlacement>().HasData(
     new AddPlacement { ID = 1, SID = 1, RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), PlaceCode = "PATH", PlaceName = "Pathology", UId = 1, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 2, SID = 2, RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), PlaceCode = "RAD", PlaceName = "Radiology", UId = 2, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 3, SID = 3, RegDate = DateTime.Parse("2020-01-18 01:15:27.000"), PlaceCode = "OPD", PlaceName = "Outpatient Department", UId = 3, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 4, SID = 4, RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), PlaceCode = "CSR", PlaceName = "Customer Service Representative", UId = 4, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 5, SID = 5, RegDate = DateTime.Parse("2021-02-28 12:10:07.000"), PlaceCode = "IT", PlaceName = "Information Technology", UId = 5, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 6, SID = 6, RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), PlaceCode = "HR", PlaceName = "Human Resources", UId = 6, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 7, SID = 7, RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), PlaceCode = "IPD", PlaceName = "Inpatient Department", UId = 7, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 8, SID = 8, RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), PlaceCode = "FIN", PlaceName = "Finance", UId = 8, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 9, SID = 9, RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), PlaceCode = "MKTG", PlaceName = "Marketing", UId = 9, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 10, SID = 9, RegDate = DateTime.Parse("2018-04-15 03:21:16.000"), PlaceCode = "SCM", PlaceName = "Supply Chain Management", UId = 9, Idloc = "Null", CompMac = "Null" },
     new AddPlacement { ID = 11, SID = null, RegDate = null, PlaceCode = "MED", PlaceName = "Medical", UId = null, Idloc = "Null", CompMac = "Null" }
 );
            modelBuilder.Entity<AddLocation>().HasData(
    new AddLocation { ID = 1, RegDate = DateTime.Parse("2018-05-01 01:50:40.000"), LocActive = "Yes", LocID = 10150121, LocCate = "Main", Reconsile = "Active", Location = "Main", LocSno = 0, UId = 1, Idloc = "NKM", CompMac = "FB: Address Contact" }
);
            modelBuilder.Entity<AddConnLab>().HasData(
    new AddConnLab { ID = 5, RegDate = DateTime.Parse("2019-03-25 11:43:59.000"), LocActive = "Yes", LocID = 1, LocCate = "MAIN-LAB", Location = "MAIN-LAB", UId = null, Idloc = null, CompMac = null }
);
            modelBuilder.Entity<AccessRight>().HasData(
new AccessRight { ID = 1, SOR = 1, EmpID = 1, Assigning = "Deshboard Header Administrator" },
new AccessRight { ID = 2, SOR = 2, EmpID = 1, Assigning = "Deshboard Header Order Booking" },
new AccessRight { ID = 3, SOR = 5, EmpID = 1, Assigning = "Deshboard Header Pathology" },
new AccessRight { ID = 4, SOR = 6, EmpID = 1, Assigning = "Deshboard Header Radiology" },
new AccessRight { ID = 5, SOR = 7, EmpID = 1, Assigning = "Deshboard Header User Information" },
new AccessRight { ID = 6, SOR = 8, EmpID = 1, Assigning = "Deshboard Header Human Resources" },
new AccessRight { ID = 7, SOR = 12, EmpID = 1, Assigning = "Deshboard Header OPD" },
new AccessRight { ID = 8, SOR = 15, EmpID = 1, Assigning = "Deshboard Header SMS" },
new AccessRight { ID = 9, SOR = 19, EmpID = 1, Assigning = "Deshboard Header Loyalti" },
new AccessRight { ID = 10, SOR = 21, EmpID = 1, Assigning = "Deshboard Header Marketing" },
new AccessRight { ID = 11, SOR = 22, EmpID = 1, Assigning = "Deshboard Header CSR" },
new AccessRight { ID = 12, SOR = 25, EmpID = 1, Assigning = "Deshboard Header Company Deshboard" },
new AccessRight { ID = 13, SOR = 51, EmpID = 1, Assigning = "Administrator MenuStrip Employee Information" },
new AccessRight { ID = 14, SOR = 52, EmpID = 1, Assigning = "Administrator MenuStrip Client Registration" },
new AccessRight { ID = 15, SOR = 53, EmpID = 1, Assigning = "Administrator MenuStrip Change Reporting Date" },
new AccessRight { ID = 16, SOR = 54, EmpID = 1, Assigning = "Administrator MenuStrip Panal Dues Received" },
new AccessRight { ID = 17, SOR = 55, EmpID = 1, Assigning = "Administrator MenuStrip Expenses" },
new AccessRight { ID = 18, SOR = 56, EmpID = 1, Assigning = "Administrator MenuStrip Admin LOV" },
new AccessRight { ID = 19, SOR = 57, EmpID = 1, Assigning = "Administrator MenuStrip Department LOV" },
new AccessRight { ID = 20, SOR = 58, EmpID = 1, Assigning = "Administrator MenuStrip Pateint Payment Refund" },
new AccessRight { ID = 21, SOR = 59, EmpID = 1, Assigning = "Administrator MenuStrip Description Cancellation" },
new AccessRight { ID = 22, SOR = 60, EmpID = 1, Assigning = "Administrator MenuStrip My Company Detail" },
new AccessRight { ID = 23, SOR = 61, EmpID = 1, Assigning = "Administrator MenuStrip Check Out List" },
new AccessRight { ID = 24, SOR = 62, EmpID = 1, Assigning = "Administrator MenuStrip Finance Report" },
new AccessRight { ID = 25, SOR = 64, EmpID = 1, Assigning = "Finance Report TextBox Location" },
new AccessRight { ID = 26, SOR = 65, EmpID = 1, Assigning = "Administrator MenuStrip Change to Client" },
new AccessRight { ID = 27, SOR = 66, EmpID = 1, Assigning = "Administrator MenuStrip User Summary" },
new AccessRight { ID = 28, SOR = 67, EmpID = 1, Assigning = "Administrator MenuStrip Pdf Regenerate" },
new AccessRight { ID = 29, SOR = 68, EmpID = 1, Assigning = "Administrator MenuStrip Invoices Update Log" },
new AccessRight { ID = 30, SOR = 69, EmpID = 1, Assigning = "Administrator MenuStrip Report Forword to ERM" },
new AccessRight { ID = 31, SOR = 76, EmpID = 1, Assigning = "Administrator MenuStrip Adjust Sample CNL" },
new AccessRight { ID = 32, SOR = 80, EmpID = 1, Assigning = "Administrator MenuStrip Cancellation Update" },
new AccessRight { ID = 33, SOR = 82, EmpID = 1, Assigning = "Administrator MenuStrip OTP" },
new AccessRight { ID = 34, SOR = 83, EmpID = 1, Assigning = "Administrator MenuStrip Manual Editing" },
new AccessRight { ID = 35, SOR = 85, EmpID = 1, Assigning = "Administrator MenuStrip Add Client Approval" },
new AccessRight { ID = 36, SOR = 86, EmpID = 1, Assigning = "Administrator MenuStrip Add User Approval" },
new AccessRight { ID = 37, SOR = 89, EmpID = 1, Assigning = "Administrator MenuStrip Bulk Sample Transfer" },
new AccessRight { ID = 38, SOR = 92, EmpID = 1, Assigning = "Administrator MenuStrip Franchise Client Registration" },
new AccessRight { ID = 39, SOR = 93, EmpID = 1, Assigning = "Administrator MenuStrip Interlink Management" },
new AccessRight { ID = 40, SOR = 101, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Status" },
new AccessRight { ID = 41, SOR = 102, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Location" },
new AccessRight { ID = 42, SOR = 103, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Description" },
new AccessRight { ID = 43, SOR = 104, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Depart" },
new AccessRight { ID = 44, SOR = 105, EmpID = 1, Assigning = "AdminLOV MenuStrip Add SubDepart" },
new AccessRight { ID = 45, SOR = 106, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Consultant" },
new AccessRight { ID = 46, SOR = 107, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Section" },
new AccessRight { ID = 47, SOR = 108, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Place" },
new AccessRight { ID = 48, SOR = 109, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Place Category" },
new AccessRight { ID = 49, SOR = 110, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Designation" },
new AccessRight { ID = 50, SOR = 111, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Expenser Name" },
new AccessRight { ID = 51, SOR = 112, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Expenses Purpose" },
new AccessRight { ID = 52, SOR = 113, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Connecting Lab" },
new AccessRight { ID = 53, SOR = 114, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Other Lab Send Sample" },
new AccessRight { ID = 54, SOR = 115, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Discount Athorities" },
new AccessRight { ID = 55, SOR = 116, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Editable Athorities" },
new AccessRight { ID = 56, SOR = 117, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Balance Athorities" },
new AccessRight { ID = 57, SOR = 118, EmpID = 1, Assigning = "AdminLOV MenuStrip Invoice Update of New RateList" },
new AccessRight { ID = 58, SOR = 120, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Location Athorities" },
new AccessRight { ID = 59, SOR = 121, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Country" },
new AccessRight { ID = 60, SOR = 122, EmpID = 1, Assigning = "AdminLOV MenuStrip Add City" },
new AccessRight { ID = 61, SOR = 123, EmpID = 1, Assigning = "AdminLOV MenuStrip Add Area" },
new AccessRight { ID = 62, SOR = 124, EmpID = 1, Assigning = "AdminLOV MenuStrip Add DrStamp" },
new AccessRight { ID = 63, SOR = 151, EmpID = 1, Assigning = "Department LOV MenuStrip Add Page LOV" },
new AccessRight { ID = 64, SOR = 152, EmpID = 1, Assigning = "Department LOV MenuStrip Add Culture Short Key" },
new AccessRight { ID = 65, SOR = 155, EmpID = 1, Assigning = "Department LOV MenuStrip Change Description Setting" },
new AccessRight { ID = 66, SOR = 201, EmpID = 1, Assigning = "Order Booking MenuStrip Main Reception" },
new AccessRight { ID = 67, SOR = 203, EmpID = 1, Assigning = "Order Booking MenuStrip Report Status" },
new AccessRight { ID = 68, SOR = 204, EmpID = 1, Assigning = "Order Booking MenuStrip Summary Status" },
new AccessRight { ID = 69, SOR = 205, EmpID = 1, Assigning = "Order Booking MenuStrip Rate Slip" },
new AccessRight { ID = 70, SOR = 209, EmpID = 1, Assigning = "Order Booking MenuStrip OPD Reception" },
new AccessRight { ID = 71, SOR = 210, EmpID = 1, Assigning = "Order Booking MenuStrip Appointment Registration" },
new AccessRight { ID = 72, SOR = 211, EmpID = 1, Assigning = "Order Booking MenuStrip Appointment Status" },
new AccessRight { ID = 73, SOR = 212, EmpID = 1, Assigning = "Order Booking MenuStrip Government Summary For Covid" },
new AccessRight { ID = 74, SOR = 213, EmpID = 1, Assigning = "Order Booking MenuStrip Make Client PDFs" },
new AccessRight { ID = 75, SOR = 216, EmpID = 1, Assigning = "Order Booking MenuStrip Resource Request Form" },
new AccessRight { ID = 76, SOR = 225, EmpID = 1, Assigning = "Order Editing MenuStrip Edit Flight Detail" },
new AccessRight { ID = 77, SOR = 226, EmpID = 1, Assigning = "Order Editing MenuStrip Edit Cash Detail" },
new AccessRight { ID = 78, SOR = 227, EmpID = 1, Assigning = "Order Editing MenuStrip Edit Client Detail" },
new AccessRight { ID = 79, SOR = 240, EmpID = 1, Assigning = "Patient Registration Button Edit" },
new AccessRight { ID = 80, SOR = 351, EmpID = 1, Assigning = "Pathology MenuStrip Phlebotomy Acknowledge" },
new AccessRight { ID = 81, SOR = 352, EmpID = 1, Assigning = "Pathology MenuStrip Section Acknowledge" },
new AccessRight { ID = 82, SOR = 353, EmpID = 1, Assigning = "Pathology MenuStrip Batch Generate" },
new AccessRight { ID = 83, SOR = 354, EmpID = 1, Assigning = "Pathology MenuStrip Batch Received" },
new AccessRight { ID = 84, SOR = 355, EmpID = 1, Assigning = "Pathology MenuStrip Pathology Reporting" },
new AccessRight { ID = 85, SOR = 356, EmpID = 1, Assigning = "Pathology MenuStrip Serological Reporting" },
new AccessRight { ID = 86, SOR = 357, EmpID = 1, Assigning = "Pathology MenuStrip Molecular Pathology" },
new AccessRight { ID = 87, SOR = 358, EmpID = 1, Assigning = "Pathology MenuStrip Send Sample" },
new AccessRight { ID = 88, SOR = 359, EmpID = 1, Assigning = "Pathology MenuStrip True Follow Acknowlegdement" },
new AccessRight { ID = 89, SOR = 370, EmpID = 1, Assigning = "Pathology MenuStrip Select a Change Status" },
new AccessRight { ID = 90, SOR = 371, EmpID = 1, Assigning = "Pathology MenuStrip Lab Number Release" },
new AccessRight { ID = 91, SOR = 372, EmpID = 1, Assigning = "Pathology MenuStrip Average Report" },
new AccessRight { ID = 92, SOR = 373, EmpID = 1, Assigning = "Pathology MenuStrip Home Sample Received" },
new AccessRight { ID = 93, SOR = 376, EmpID = 1, Assigning = "Pathology MenuStrip Sample Tracking System" },
new AccessRight { ID = 94, SOR = 379, EmpID = 1, Assigning = "Pathology MenuStrip Sample Rejection" },
new AccessRight { ID = 95, SOR = 402, EmpID = 1, Assigning = "Radiology MenuStrip Radiology Reporting" },
new AccessRight { ID = 96, SOR = 403, EmpID = 1, Assigning = "Radiology MenuStrip Average Report" },
new AccessRight { ID = 97, SOR = 451, EmpID = 1, Assigning = "User Information MenuStrip User Registration" },
new AccessRight { ID = 98, SOR = 452, EmpID = 1, Assigning = "User Information MenuStrip Again Login" },
new AccessRight { ID = 99, SOR = 453, EmpID = 1, Assigning = "User Information MenuStrip Change Password" },
new AccessRight { ID = 100, SOR = 501, EmpID = 1, Assigning = "Human Resources MenuStrip Attendance Record" },
new AccessRight { ID = 101, SOR = 502, EmpID = 1, Assigning = "Human Resources MenuStrip Add Salary" },
new AccessRight { ID = 102, SOR = 503, EmpID = 1, Assigning = "Human Resources MenuStrip Pay Slip Print" },
new AccessRight { ID = 103, SOR = 504, EmpID = 1, Assigning = "Human Resources MenuStrip Add Loan Deducation" },
new AccessRight { ID = 104, SOR = 505, EmpID = 1, Assigning = "Human Resources MenuStrip Add Holiday" },
new AccessRight { ID = 105, SOR = 506, EmpID = 1, Assigning = "Human Resources MenuStrip Generate Pay Slip" },
new AccessRight { ID = 106, SOR = 507, EmpID = 1, Assigning = "Connectivity MenuStrip Crystal Report Path" },
new AccessRight { ID = 107, SOR = 510, EmpID = 1, Assigning = "Human Resources MenuStrip Add Leave" },
new AccessRight { ID = 108, SOR = 520, EmpID = 1, Assigning = "Attendance Record TextBox Location" },
new AccessRight { ID = 109, SOR = 521, EmpID = 1, Assigning = "Human Resources MenuStrip Thumb Attendance Record" },
new AccessRight { ID = 110, SOR = 561, EmpID = 1, Assigning = "Pateint Cancellation Button Find" },
new AccessRight { ID = 111, SOR = 562, EmpID = 1, Assigning = "Pateint Cancellation Button Update" },
new AccessRight { ID = 112, SOR = 563, EmpID = 1, Assigning = "Pateint Cancellation Button Print" },
new AccessRight { ID = 113, SOR = 564, EmpID = 1, Assigning = "User Summary TextBox User ID Box" },
new AccessRight { ID = 114, SOR = 601, EmpID = 1, Assigning = "Pateint Payment Refund Button Find" },
new AccessRight { ID = 115, SOR = 602, EmpID = 1, Assigning = "Pateint Payment Refund Button Update" },
new AccessRight { ID = 116, SOR = 603, EmpID = 1, Assigning = "Pateint Payment Refund Button Print" },
new AccessRight { ID = 117, SOR = 651, EmpID = 1, Assigning = "Employee Personal Information Button Find" },
new AccessRight { ID = 118, SOR = 652, EmpID = 1, Assigning = "Employee Personal Information Button Save" },
new AccessRight { ID = 119, SOR = 653, EmpID = 1, Assigning = "Employee Personal Information Button Print" },
new AccessRight { ID = 120, SOR = 654, EmpID = 1, Assigning = "Employee Personal Information Button Edit" },
new AccessRight { ID = 121, SOR = 701, EmpID = 1, Assigning = "Client Registration Button Find" },
new AccessRight { ID = 122, SOR = 702, EmpID = 1, Assigning = "Client Registration Button Save" },
new AccessRight { ID = 123, SOR = 703, EmpID = 1, Assigning = "Client Registration Button Print" },
new AccessRight { ID = 124, SOR = 704, EmpID = 1, Assigning = "Client Registration Button Edit" },
new AccessRight { ID = 125, SOR = 705, EmpID = 1, Assigning = "Client Registration Button Desc Link Visiable" },
new AccessRight { ID = 126, SOR = 706, EmpID = 1, Assigning = "Client Registration CheckBox Price Change Visiable" },
new AccessRight { ID = 127, SOR = 707, EmpID = 1, Assigning = "Client Registration TextBox Location" },
new AccessRight { ID = 128, SOR = 751, EmpID = 1, Assigning = "Add Client Description Button Find" },
new AccessRight { ID = 129, SOR = 752, EmpID = 1, Assigning = "Add Client Description Button Save" },
new AccessRight { ID = 130, SOR = 753, EmpID = 1, Assigning = "Add Client Description Button Print" },
new AccessRight { ID = 131, SOR = 754, EmpID = 1, Assigning = "Add Client Description Button Edit" },
new AccessRight { ID = 132, SOR = 755, EmpID = 1, Assigning = "Add Client Description Button Apply" },
new AccessRight { ID = 133, SOR = 756, EmpID = 1, Assigning = "Add Client Description Button Forword" },
new AccessRight { ID = 134, SOR = 757, EmpID = 1, Assigning = "Add Client Description Button Selected All" },
new AccessRight { ID = 135, SOR = 758, EmpID = 1, Assigning = "Add Client Description Button Selected None" },
new AccessRight { ID = 136, SOR = 801, EmpID = 1, Assigning = "Main Reception Button Find" },
new AccessRight { ID = 137, SOR = 802, EmpID = 1, Assigning = "Main Reception Button Save" },
new AccessRight { ID = 138, SOR = 803, EmpID = 1, Assigning = "Main Reception Button Apply" },
new AccessRight { ID = 139, SOR = 804, EmpID = 1, Assigning = "Main Reception Button Edit" },
new AccessRight { ID = 140, SOR = 805, EmpID = 1, Assigning = "Main Reception Button Update" },
new AccessRight { ID = 141, SOR = 806, EmpID = 1, Assigning = "Main Reception Button Print" },
new AccessRight { ID = 142, SOR = 807, EmpID = 1, Assigning = "Main Reception Button Barcode" },
new AccessRight { ID = 143, SOR = 808, EmpID = 1, Assigning = "Main Reception ComboBox DiscBox" },
new AccessRight { ID = 144, SOR = 810, EmpID = 1, Assigning = "Main Reception Button Delete" },
new AccessRight { ID = 145, SOR = 851, EmpID = 1, Assigning = "Blood Bank Reception Button Barcode" },
new AccessRight { ID = 146, SOR = 852, EmpID = 1, Assigning = "Blood Bank Reception Button Save" },
new AccessRight { ID = 147, SOR = 853, EmpID = 1, Assigning = "Blood Bank Reception Button Edit" },
new AccessRight { ID = 148, SOR = 854, EmpID = 1, Assigning = "Blood Bank Reception Button Update" },
new AccessRight { ID = 149, SOR = 855, EmpID = 1, Assigning = "Blood Bank Reception Button Print" },
new AccessRight { ID = 150, SOR = 901, EmpID = 1, Assigning = "Report Status Button Print" },
new AccessRight { ID = 151, SOR = 902, EmpID = 1, Assigning = "Report Status Button PrintView" },
new AccessRight { ID = 152, SOR = 951, EmpID = 1, Assigning = "Summary Status TextBox Location" },
new AccessRight { ID = 153, SOR = 952, EmpID = 1, Assigning = "Summary Status TextBox Department" },
new AccessRight { ID = 154, SOR = 953, EmpID = 1, Assigning = "Summary Status TextBox Placement" },
new AccessRight { ID = 155, SOR = 954, EmpID = 1, Assigning = "Summary Status Button Department DataEntry Sheet" },
new AccessRight { ID = 156, SOR = 955, EmpID = 1, Assigning = "Summary Status TextBox Client Name" },
new AccessRight { ID = 157, SOR = 956, EmpID = 1, Assigning = "Summary Status TextBox User Name" },
new AccessRight { ID = 158, SOR = 1001, EmpID = 1, Assigning = "Reporting Procedure Button Save" },
new AccessRight { ID = 159, SOR = 1002, EmpID = 1, Assigning = "Reporting Procedure Button Perform" },
new AccessRight { ID = 160, SOR = 1004, EmpID = 1, Assigning = "Reporting Procedure Button Forword" },
new AccessRight { ID = 161, SOR = 1005, EmpID = 1, Assigning = "Reporting Procedure Button Partially Verification" },
new AccessRight { ID = 162, SOR = 1006, EmpID = 1, Assigning = "Reporting Procedure TextBox Department" },
new AccessRight { ID = 163, SOR = 1051, EmpID = 1, Assigning = "Pharmacy Reception Button Save" },
new AccessRight { ID = 164, SOR = 1052, EmpID = 1, Assigning = "Pharmacy Reception Button Edit" },
new AccessRight { ID = 165, SOR = 1053, EmpID = 1, Assigning = "Pharmacy Reception Button Print" },
new AccessRight { ID = 166, SOR = 1101, EmpID = 1, Assigning = "Serological Reporting Button Perform" },
new AccessRight { ID = 167, SOR = 1102, EmpID = 1, Assigning = "Serological Reporting Button Save" },
new AccessRight { ID = 168, SOR = 1103, EmpID = 1, Assigning = "Serological Reporting Button Forword" },
new AccessRight { ID = 169, SOR = 1104, EmpID = 1, Assigning = "Serological Reporting Button Partially Verification" },
new AccessRight { ID = 170, SOR = 1105, EmpID = 1, Assigning = "Serological Reporting TextBox Department" },
new AccessRight { ID = 171, SOR = 1106, EmpID = 1, Assigning = "Serological Reporting TextBox Location" },
new AccessRight { ID = 172, SOR = 1151, EmpID = 1, Assigning = "Molecular Pathology Button Perform" },
new AccessRight { ID = 173, SOR = 1152, EmpID = 1, Assigning = "Molecular Pathology Button Save" },
new AccessRight { ID = 174, SOR = 1153, EmpID = 1, Assigning = "Molecular Pathology Button Forword" },
new AccessRight { ID = 175, SOR = 1154, EmpID = 1, Assigning = "Molecular Pathology Button Partially Verification" },
new AccessRight { ID = 176, SOR = 1155, EmpID = 1, Assigning = "Molecular Pathology TextBox Department" },
new AccessRight { ID = 177, SOR = 1156, EmpID = 1, Assigning = "Molecular Pathology TextBox Location" },
new AccessRight { ID = 178, SOR = 1201, EmpID = 1, Assigning = "Pathology Reporting Button Perform" },
new AccessRight { ID = 179, SOR = 1202, EmpID = 1, Assigning = "Pathology Reporting Button Final Verification" },
new AccessRight { ID = 180, SOR = 1203, EmpID = 1, Assigning = "Pathology Reporting Button Hold" },
new AccessRight { ID = 181, SOR = 1204, EmpID = 1, Assigning = "Pathology Reporting Button Partially Verification" },
new AccessRight { ID = 182, SOR = 1205, EmpID = 1, Assigning = "Pathology Reporting TextBox Department" },
new AccessRight { ID = 183, SOR = 1206, EmpID = 1, Assigning = "Pathology Reporting TextBox Location" },
new AccessRight { ID = 184, SOR = 1207, EmpID = 1, Assigning = "Pathology Reporting Button Result Delete" },
new AccessRight { ID = 185, SOR = 1210, EmpID = 1, Assigning = "Pathology Reporting Button Save" },
new AccessRight { ID = 186, SOR = 1212, EmpID = 1, Assigning = "Pathology Reporting TextBox CNL" },
new AccessRight { ID = 187, SOR = 1251, EmpID = 1, Assigning = "CultureSensitivity Button Save" },
new AccessRight { ID = 188, SOR = 1252, EmpID = 1, Assigning = "CultureSensitivity Button Perform" },
new AccessRight { ID = 189, SOR = 1253, EmpID = 1, Assigning = "CultureSensitivity Button Forword" },
new AccessRight { ID = 190, SOR = 1254, EmpID = 1, Assigning = "CultureSensitivity Button Partially Verification" },
new AccessRight { ID = 191, SOR = 1255, EmpID = 1, Assigning = "CultureSensitivity Button Delete Gram Stain" },
new AccessRight { ID = 192, SOR = 1256, EmpID = 1, Assigning = "CultureSensitivity Button Delete Orgnasium" },
new AccessRight { ID = 193, SOR = 1257, EmpID = 1, Assigning = "CultureSensitivity Button Delete Medician" },
new AccessRight { ID = 194, SOR = 1258, EmpID = 1, Assigning = "Average Report TextBox Location" },
new AccessRight { ID = 195, SOR = 1259, EmpID = 1, Assigning = "Average Report TextBox Department" },
new AccessRight { ID = 196, SOR = 1260, EmpID = 1, Assigning = "Average Report TextBox Sub Department" },
new AccessRight { ID = 197, SOR = 1301, EmpID = 1, Assigning = "RadiologyReporting Button Final Verification" },
new AccessRight { ID = 198, SOR = 1302, EmpID = 1, Assigning = "RadiologyReporting Button Hold" },
new AccessRight { ID = 199, SOR = 1305, EmpID = 1, Assigning = "RadiologyReporting TextBox Department" },
new AccessRight { ID = 200, SOR = 1306, EmpID = 1, Assigning = "RadiologyReporting TextBox Location" },
new AccessRight { ID = 201, SOR = 1307, EmpID = 1, Assigning = "RadiologyReporting Button Result Delete" },
new AccessRight { ID = 202, SOR = 1351, EmpID = 1, Assigning = "Ultrasound All Button Save" },
new AccessRight { ID = 203, SOR = 1401, EmpID = 1, Assigning = "Ultrasound FWB Button Save" },
new AccessRight { ID = 204, SOR = 1451, EmpID = 1, Assigning = "Xray Button Save" },
new AccessRight { ID = 205, SOR = 1501, EmpID = 1, Assigning = "Chart of Account MenuStrip Vouchers" },
new AccessRight { ID = 206, SOR = 1502, EmpID = 1, Assigning = "Chart of Account MenuStrip Add Head of Account" },
new AccessRight { ID = 207, SOR = 1503, EmpID = 1, Assigning = "Chart of Account MenuStrip Report Summary" },
new AccessRight { ID = 208, SOR = 1550, EmpID = 1, Assigning = "Inventory MenuStrip Delivery" },
new AccessRight { ID = 209, SOR = 1551, EmpID = 1, Assigning = "Inventory MenuStrip Request" },
new AccessRight { ID = 210, SOR = 1552, EmpID = 1, Assigning = "Inventory MenuStrip Status Book" },
new AccessRight { ID = 211, SOR = 1553, EmpID = 1, Assigning = "Inventory MenuStrip General Stock" },
new AccessRight { ID = 212, SOR = 1554, EmpID = 1, Assigning = "Inventory MenuStrip Medical Stock" },
new AccessRight { ID = 213, SOR = 1555, EmpID = 1, Assigning = "Inventory MenuStrip Manual Barcode" },
new AccessRight { ID = 214, SOR = 1556, EmpID = 1, Assigning = "Inventory MenuStrip Accountibility" },
new AccessRight { ID = 215, SOR = 1557, EmpID = 1, Assigning = "Inventory MenuStrip Add Product" },
new AccessRight { ID = 216, SOR = 1558, EmpID = 1, Assigning = "Inventory MenuStrip Opening Balance" },
new AccessRight { ID = 217, SOR = 1559, EmpID = 1, Assigning = "Inventory MenuStrip Activity Report" },
new AccessRight { ID = 218, SOR = 1560, EmpID = 1, Assigning = "Inventory MenuStrip Stock Report" },
new AccessRight { ID = 219, SOR = 1600, EmpID = 1, Assigning = "Setting MenuStrip System Configration" },
new AccessRight { ID = 220, SOR = 1650, EmpID = 1, Assigning = "OPD MenuStrip OPD Reporting" },
new AccessRight { ID = 221, SOR = 1651, EmpID = 1, Assigning = "Expenses Button Edit" },
new AccessRight { ID = 222, SOR = 1652, EmpID = 1, Assigning = "Expenses TextBox Date" },
new AccessRight { ID = 223, SOR = 1653, EmpID = 1, Assigning = "Expenses Button Delete" },
new AccessRight { ID = 224, SOR = 1700, EmpID = 1, Assigning = "HistoPathology Button Perform" },
new AccessRight { ID = 225, SOR = 1750, EmpID = 1, Assigning = "Section Acknowlegde Button Pending" },
new AccessRight { ID = 226, SOR = 1751, EmpID = 1, Assigning = "Section Acknowlegde Button Section Ack" },
new AccessRight { ID = 227, SOR = 1801, EmpID = 1, Assigning = "Phlebotomy Acknowledge Button Pending" },
new AccessRight { ID = 228, SOR = 1850, EmpID = 1, Assigning = "Batch Received Button Pending" },
new AccessRight { ID = 229, SOR = 1851, EmpID = 1, Assigning = "Batch Received Button Batch Received" },
new AccessRight { ID = 230, SOR = 1901, EmpID = 1, Assigning = "Batch Generate Button Pending" },
new AccessRight { ID = 231, SOR = 1902, EmpID = 1, Assigning = "Batch Generate Button Batch Generate" },
new AccessRight { ID = 232, SOR = 1952, EmpID = 1, Assigning = "Check Out TextBox UserID" },
new AccessRight { ID = 233, SOR = 1953, EmpID = 1, Assigning = "Check Out TextBox Location" },
new AccessRight { ID = 234, SOR = 2001, EmpID = 1, Assigning = "SMS MenuStrip Setting" },
new AccessRight { ID = 235, SOR = 2002, EmpID = 1, Assigning = "SMS MenuStrip SMS Sender" },
new AccessRight { ID = 236, SOR = 2003, EmpID = 1, Assigning = "SMS MenuStrip Empolyee SMS" },
new AccessRight { ID = 237, SOR = 2400, EmpID = 1, Assigning = "Purchase MenuStrip Request" },
new AccessRight { ID = 238, SOR = 2401, EmpID = 1, Assigning = "Purchase MenuStrip Order" },
new AccessRight { ID = 239, SOR = 2402, EmpID = 1, Assigning = "Purchase MenuStrip Vendor Registration" },
new AccessRight { ID = 240, SOR = 2403, EmpID = 1, Assigning = "Vendor Registration MenuStrip Add Vendor" },
new AccessRight { ID = 241, SOR = 2451, EmpID = 1, Assigning = "Loyalti MenuStrip Company Setup" },
new AccessRight { ID = 242, SOR = 2452, EmpID = 1, Assigning = "Loyalti MenuStrip Card Setup" },
new AccessRight { ID = 243, SOR = 2501, EmpID = 1, Assigning = "Marketing TextBox User or Location" }
); 
            modelBuilder.Entity<AddDepart>().HasData(
    new AddDepart { ID = 116, SID = 77, RegDate = DateTime.Parse("2021-12-16 04:28:58.000"), Location = null, Placement = "IPD", Depart = "Gynee", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 117, SID = 78, RegDate = DateTime.Parse("2021-12-16 04:46:16.000"), Location = null, Placement = "IPD", Depart = "NICU", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 34, SID = 15, RegDate = DateTime.Parse("2020-01-13 22:25:06.000"), Location = "GB", Placement = "IT", Depart = "ALL", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 77, SID = 46, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "IT", Depart = "IT", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 114, SID = 75, RegDate = DateTime.Parse("2021-12-16 04:21:44.000"), Location = null, Placement = "OPD", Depart = "Consultancy", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 115, SID = 76, RegDate = DateTime.Parse("2021-12-16 04:21:44.000"), Location = null, Placement = "OPD", Depart = "RMO", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 119, SID = 80, RegDate = DateTime.Parse("2021-12-16 04:21:44.000"), Location = "GB", Placement = "OPD", Depart = "Services", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 118, SID = 79, RegDate = DateTime.Parse("2022-01-13 13:53:56.000"), Location = null, Placement = "OPD", Depart = "Ultrasound", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 1, SID = 1, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "PATH", Depart = "BIOCHEMISTRY", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 2, SID = 2, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "PATH", Depart = "BLOOD BANK", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 49, SID = 30, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "PATH", Depart = "HEMATOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 3, SID = 3, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "PATH", Depart = "HISTOPATHOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 4, SID = 4, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "PATH", Depart = "MICROBIOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 5, SID = 5, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "PATH", Depart = "MOLECULAR PATHOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 7, SID = 7, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "RAD", Depart = "CT SCAN", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 8, SID = 8, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "RAD", Depart = "ECG", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 10, SID = 10, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "RAD", Depart = "ECHO", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 11, SID = 11, RegDate = DateTime.Parse("2018-04-20 03:07:29.000"), Location = "GB", Placement = "RAD", Depart = "MRI", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 31, SID = 13, RegDate = DateTime.Parse("2018-04-15 02:42:02.233"), Location = "GB", Placement = "RAD", Depart = "ULTRASOUND", UId = null, Idloc = null, CompMac = null },
    new AddDepart { ID = 32, SID = 14, RegDate = DateTime.Parse("2018-04-15 02:42:02.233"), Location = "GB", Placement = "RAD", Depart = "X-RAY", UId = null, Idloc = null, CompMac = null }
    // Add other entries as needed...
); modelBuilder.Entity<AddSubDepart>().HasData(
    new AddSubDepart { ID = 121, SID = 7, RegDate = DateTime.Parse("2021-12-16 04:41:43.000"), Location = "IPD", Depart = "Gynee", SubDepart = "Labour Room", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 120, SID = 6, RegDate = DateTime.Parse("2021-12-16 04:34:19.000"), Location = "IPD", Depart = "Gynee", SubDepart = "Operation", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 123, SID = 9, RegDate = DateTime.Parse("2021-12-16 04:46:33.000"), Location = "IPD", Depart = "NICU", SubDepart = "Admission", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 122, SID = 8, RegDate = DateTime.Parse("2021-12-16 04:46:33.000"), Location = "IPD", Depart = "NICU", SubDepart = "Observation", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 40, SID = 37, RegDate = DateTime.Parse("2021-05-11 12:31:38.000"), Location = "IT", Depart = "IT", SubDepart = "Governance", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 31, SID = 29, RegDate = DateTime.Parse("2021-05-11 12:31:38.000"), Location = "IT", Depart = "IT", SubDepart = "Infrastructure Department", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 29, SID = 27, RegDate = DateTime.Parse("2021-02-02 21:15:19.000"), Location = "IT", Depart = "IT", SubDepart = "Operation and Maintenance", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 72, SID = 69, RegDate = DateTime.Parse("2021-02-02 21:15:19.000"), Location = "IT", Depart = "IT", SubDepart = "Software Development", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 116, SID = 2, RegDate = DateTime.Parse("2021-12-16 04:29:48.000"), Location = "OPD", Depart = "Consultancy", SubDepart = "Cardiology", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 125, SID = 11, RegDate = DateTime.Parse("2021-12-16 04:46:33.000"), Location = "OPD", Depart = "Consultancy", SubDepart = "Dentist", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 115, SID = 1, RegDate = DateTime.Parse("2021-12-16 04:29:48.000"), Location = "OPD", Depart = "Consultancy", SubDepart = "Diabetes", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 117, SID = 3, RegDate = DateTime.Parse("2021-12-16 04:29:48.000"), Location = "OPD", Depart = "Consultancy", SubDepart = "ENT", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 126, SID = 12, RegDate = DateTime.Parse("2022-01-15 12:51:45.000"), Location = "OPD", Depart = "Consultancy", SubDepart = "General", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 124, SID = 10, RegDate = DateTime.Parse("2021-12-16 04:46:33.000"), Location = "OPD", Depart = "Consultancy", SubDepart = "Gynecology", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 118, SID = 4, RegDate = DateTime.Parse("2021-12-16 04:29:48.000"), Location = "OPD", Depart = "RMO", SubDepart = "General", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 119, SID = 5, RegDate = DateTime.Parse("2021-12-16 04:29:48.000"), Location = "OPD", Depart = "Services", SubDepart = "Services", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 79, SID = 74, RegDate = DateTime.Parse("2021-05-10 16:13:47.000"), Location = "PATH", Depart = "Admin", SubDepart = "Transport", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 2, SID = 2, RegDate = DateTime.Parse("2019-07-07 16:30:43.000"), Location = "Path", Depart = "BIOCHEMISTRY", SubDepart = "ROUTINE CHEMISTRY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 1, SID = 1, RegDate = DateTime.Parse("2018-04-15 02:35:57.000"), Location = "Path", Depart = "BIOCHEMISTRY", SubDepart = "SPECIAL CHEMISTRY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 24, SID = 22, RegDate = DateTime.Parse("2018-04-15 02:35:57.000"), Location = "Path", Depart = "BIOCHEMISTRY", SubDepart = "SPECIAL CHEMISTRY / IMMUNOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 27, SID = 25, RegDate = DateTime.Parse("2018-04-15 02:35:57.000"), Location = "Path", Depart = "BIOCHEMISTRY", SubDepart = "SPECIAL CHEMISTRY / IMMUNOLOGY / OUT SIDE", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 25, SID = 23, RegDate = DateTime.Parse("2018-04-15 02:35:57.000"), Location = "PATH", Depart = "BIOCHEMISTRY", SubDepart = "SPECIAL CHEMISTRY / OUT SIDE", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 76, SID = 71, RegDate = DateTime.Parse("2021-12-27 19:39:29.000"), Location = "PATH", Depart = "Distribution", SubDepart = "Bulk Dispatch", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 75, SID = 70, RegDate = DateTime.Parse("2021-12-27 19:39:29.000"), Location = "PATH", Depart = "Distribution", SubDepart = "Routine Dispatch", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 28, SID = 26, RegDate = null, Location = "Path", Depart = "HEMATOLOGY", SubDepart = "HEMATOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 26, SID = 24, RegDate = DateTime.Parse("2020-07-15 00:15:01.000"), Location = "PATH", Depart = "HISTOPATHOLOGY", SubDepart = "CYTOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 4, SID = 4, RegDate = null, Location = "Path", Depart = "HISTOPATHOLOGY", SubDepart = "HISTOPATHOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 5, SID = 5, RegDate = null, Location = "Path", Depart = "MICROBIOLOGY", SubDepart = "BACTERIOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 18, SID = 16, RegDate = null, Location = "Path", Depart = "MICROBIOLOGY", SubDepart = "Culture Sensitivity", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 6, SID = 6, RegDate = null, Location = "Path", Depart = "MICROBIOLOGY", SubDepart = "PARASITOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 7, SID = 7, RegDate = null, Location = "Path", Depart = "MICROBIOLOGY", SubDepart = "SEROLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 23, SID = 21, RegDate = null, Location = "Path", Depart = "MOLECULAR PATHOLOGY", SubDepart = "BLOOD", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 8, SID = 8, RegDate = null, Location = "Path", Depart = "MOLECULAR PATHOLOGY", SubDepart = "MOLECULAR PATHOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 22, SID = 20, RegDate = null, Location = "Path", Depart = "MOLECULAR PATHOLOGY", SubDepart = "NASAL", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 11, SID = 9, RegDate = null, Location = "Rad", Depart = "COLOR DOPPLER", SubDepart = "COLOR DOPPLER", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 12, SID = 10, RegDate = null, Location = "Rad", Depart = "CT SCAN", SubDepart = "CT SCAN", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 35, SID = 32, RegDate = null, Location = "Rad", Depart = "Mancom", SubDepart = "Mancom", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 13, SID = 11, RegDate = null, Location = "Rad", Depart = "MRI", SubDepart = "MRI", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 71, SID = 68, RegDate = DateTime.Parse("2018-04-15 02:35:57.000"), Location = "Rad", Depart = "PHYSIOLOGY", SubDepart = "PHYSIOLOGY", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 34, SID = 32, RegDate = DateTime.Parse("2021-05-12 14:21:14.000"), Location = "Rad", Depart = "Sonology", SubDepart = "Sonology", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 16, SID = 14, RegDate = DateTime.Parse("2021-12-13 19:27:07.000"), Location = "Rad", Depart = "ULTRASOUND", SubDepart = "ULTRASOUND", UId = null, Idloc = null, CompMac = null },
    new AddSubDepart { ID = 17, SID = 15, RegDate = DateTime.Parse("2021-12-13 19:27:07.000"), Location = "Rad", Depart = "X-RAY", SubDepart = "Xray", UId = null, Idloc = null, CompMac = null }
); modelBuilder.Entity<AddDesignation>().HasData(
    new AddDesignation { ID = 132, SID = 29, RegDate = null, Designation = "IT Trainee", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 201, SID = 98, RegDate = null, Designation = "Accountant", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 150, SID = 47, RegDate = null, Designation = "Administrator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 140, SID = 37, RegDate = null, Designation = "Assistant Branch Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 167, SID = 64, RegDate = null, Designation = "Assistant Lab Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 153, SID = 50, RegDate = null, Designation = "Assistant Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 119, SID = 16, RegDate = null, Designation = "Billing Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 179, SID = 76, RegDate = null, Designation = "Branch Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 144, SID = 41, RegDate = null, Designation = "Business Development Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 138, SID = 35, RegDate = null, Designation = "Business Development Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 137, SID = 34, RegDate = null, Designation = "Business Development Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 146, SID = 43, RegDate = null, Designation = "Core Graphic Designer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 143, SID = 40, RegDate = null, Designation = "Corporate Sales Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 142, SID = 39, RegDate = null, Designation = "Corporate Sales Head", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 198, SID = 95, RegDate = null, Designation = "Critical Care Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 157, SID = 54, RegDate = null, Designation = "Customer Service Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 148, SID = 45, RegDate = null, Designation = "Digital Media Coordinator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 147, SID = 44, RegDate = null, Designation = "Digital Media Designer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 176, SID = 73, RegDate = null, Designation = "Dispatch Coordinator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 178, SID = 75, RegDate = null, Designation = "Dispatch Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 174, SID = 71, RegDate = null, Designation = "Fleet Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 149, SID = 46, RegDate = null, Designation = "Graphic Designer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 121, SID = 18, RegDate = null, Designation = "Head Of Department", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 197, SID = 94, RegDate = null, Designation = "Head Of Nurse", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 159, SID = 56, RegDate = null, Designation = "Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 127, SID = 24, RegDate = null, Designation = "IT Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 126, SID = 23, RegDate = null, Designation = "IT Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 128, SID = 25, RegDate = null, Designation = "IT Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 130, SID = 27, RegDate = null, Designation = "IT Support Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 172, SID = 69, RegDate = null, Designation = "Janitorial Coordinator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 161, SID = 58, RegDate = null, Designation = "Junior Lab Technologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 200, SID = 97, RegDate = null, Designation = "Junior Software Developer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 164, SID = 61, RegDate = null, Designation = "Lab Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 162, SID = 59, RegDate = null, Designation = "Lab Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 163, SID = 60, RegDate = null, Designation = "Lab Supervisior", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 154, SID = 51, RegDate = null, Designation = "Lab Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 160, SID = 57, RegDate = null, Designation = "Lab Technologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 133, SID = 30, RegDate = null, Designation = "Lab Trainee", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 131, SID = 28, RegDate = null, Designation = "Manager Infrastructure", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 145, SID = 42, RegDate = null, Designation = "Marketing Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 196, SID = 93, RegDate = null, Designation = "Medical Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 170, SID = 67, RegDate = null, Designation = "Office Boy", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 192, SID = 89, RegDate = null, Designation = "Phelbotomist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 151, SID = 48, RegDate = null, Designation = "Phlebotomist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 120, SID = 17, RegDate = null, Designation = "QC Manager /LAB Coordinator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 189, SID = 86, RegDate = null, Designation = "Receptionist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 155, SID = 52, RegDate = null, Designation = "Receptionist+Phlebotomist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 191, SID = 88, RegDate = null, Designation = "Recptionist/ Phelbotomist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 135, SID = 32, RegDate = null, Designation = "Regional Head Of Operations", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 136, SID = 33, RegDate = null, Designation = "Regional Sales Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 177, SID = 74, RegDate = null, Designation = "Rider", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 169, SID = 66, RegDate = null, Designation = "Senior Office Boy", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 152, SID = 49, RegDate = null, Designation = "Senior Phlebotomist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 199, SID = 96, RegDate = null, Designation = "Senior Software Developer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 165, SID = 62, RegDate = null, Designation = "Senior Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 168, SID = 65, RegDate = null, Designation = "Senior Technologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 129, SID = 26, RegDate = null, Designation = "Software Developers", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 183, SID = 80, RegDate = null, Designation = "Sonologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 190, SID = 87, RegDate = null, Designation = "Staff Nurse", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 124, SID = 21, RegDate = null, Designation = "Store Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 123, SID = 20, RegDate = null, Designation = "Store Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 122, SID = 19, RegDate = null, Designation = "Supply Chain Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 171, SID = 68, RegDate = null, Designation = "Sweeper", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 156, SID = 53, RegDate = null, Designation = "Team Leader", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 181, SID = 78, RegDate = null, Designation = "Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 166, SID = 63, RegDate = null, Designation = "Technologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 125, SID = 22, RegDate = null, Designation = "Trainee", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 139, SID = 36, RegDate = null, Designation = "Trainee", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 188, SID = 85, RegDate = null, Designation = "Trainee Assistant", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 118, SID = 15, RegDate = null, Designation = "Trainee Finance", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 184, SID = 81, RegDate = null, Designation = "Ultrasound Coordinator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 180, SID = 77, RegDate = null, Designation = "X-Ray Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 223, SID = 120, RegDate = null, Designation = "Accounts & Finance Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 214, SID = 111, RegDate = null, Designation = "Accounts Assistant / Computer Operator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 104, SID = 1, RegDate = null, Designation = "Advisor to The Board", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 217, SID = 114, RegDate = null, Designation = "Aesthetic Treatment Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 230, SID = 127, RegDate = null, Designation = "Area Sales Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 239, SID = 136, RegDate = null, Designation = "Assiatant HR & Finance", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 111, SID = 8, RegDate = null, Designation = "Assistant Manager HR/Admin", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 187, SID = 84, RegDate = null, Designation = "Assistant Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 235, SID = 132, RegDate = null, Designation = "BDO", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 116, SID = 13, RegDate = null, Designation = "Billing Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 241, SID = 138, RegDate = null, Designation = "Billing/Recovery Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 234, SID = 131, RegDate = null, Designation = "Branch Manager + Marketing", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 227, SID = 124, RegDate = null, Designation = "Branch Supervisor", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 236, SID = 133, RegDate = null, Designation = "Business Develpment Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 107, SID = 4, RegDate = null, Designation = "Chief Executive Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 113, SID = 10, RegDate = null, Designation = "Chief Financial Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 204, SID = 101, RegDate = null, Designation = "Chief Pathologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 109, SID = 6, RegDate = null, Designation = "Consultant", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 218, SID = 115, RegDate = null, Designation = "Corporate Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 216, SID = 113, RegDate = null, Designation = "CS Lead", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 222, SID = 119, RegDate = null, Designation = "CSR TEAM LEAD", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 244, SID = 141, RegDate = null, Designation = "Customer Service Team Leader", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 209, SID = 106, RegDate = null, Designation = "Data Entry Operater", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 158, SID = 55, RegDate = null, Designation = "Data Entry Operator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 173, SID = 70, RegDate = null, Designation = "Driver", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 210, SID = 107, RegDate = null, Designation = "Electrician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 240, SID = 137, RegDate = null, Designation = "Finance Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 114, SID = 11, RegDate = null, Designation = "Finance Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 117, SID = 14, RegDate = null, Designation = "Finance Trainee", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 245, SID = 142, RegDate = null, Designation = "Front Desk Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 243, SID = 140, RegDate = null, Designation = "Head of Customer Relation", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 110, SID = 7, RegDate = null, Designation = "Head Of HR / Admin", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 108, SID = 5, RegDate = null, Designation = "Head Of PCR Department", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 203, SID = 100, RegDate = null, Designation = "HR Assistant", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 112, SID = 9, RegDate = null, Designation = "HR Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 238, SID = 135, RegDate = null, Designation = "HR Intern", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 242, SID = 139, RegDate = null, Designation = "Internal Audit Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 221, SID = 118, RegDate = null, Designation = "Junior Technologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 105, SID = 2, RegDate = null, Designation = "Laboratory Director", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 246, SID = 143, RegDate = null, Designation = "Laboratory Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 205, SID = 102, RegDate = null, Designation = "Labortory Manager", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 219, SID = 116, RegDate = null, Designation = "Maintenance + Office Boy", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 233, SID = 130, RegDate = null, Designation = "Marketing Coordinator", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 225, SID = 122, RegDate = null, Designation = "Medical Consultant", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 194, SID = 91, RegDate = null, Designation = "Medical Officer", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 220, SID = 117, RegDate = null, Designation = "Micro Biologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 232, SID = 129, RegDate = null, Designation = "Molecular Lab Technologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 134, SID = 31, RegDate = null, Designation = "Network & Telecom Technician", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 212, SID = 109, RegDate = null, Designation = "Nurse", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 175, SID = 72, RegDate = null, Designation = "Office Assistant", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 106, SID = 3, RegDate = null, Designation = "Pathologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 206, SID = 103, RegDate = null, Designation = "Pathologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 237, SID = 134, RegDate = null, Designation = "Pharmacy Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 224, SID = 121, RegDate = null, Designation = "Phlebotomist + Rider", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 247, SID = 144, RegDate = null, Designation = "Procurement Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 228, SID = 125, RegDate = null, Designation = "Radiologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 229, SID = 126, RegDate = null, Designation = "Regional Head Interior", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 211, SID = 108, RegDate = null, Designation = "Regional Head- Corporate Sales", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 141, SID = 38, RegDate = null, Designation = "Regional Sales Manager Retail", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 115, SID = 12, RegDate = null, Designation = "Senior Finance Executive", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 226, SID = 123, RegDate = null, Designation = "SMO", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 231, SID = 128, RegDate = null, Designation = "Sr. BDO", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 213, SID = 110, RegDate = null, Designation = "Technical Incharge", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 215, SID = 112, RegDate = null, Designation = "Technologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 207, SID = 104, RegDate = null, Designation = "Trainee Molecular Technologist", UId = null, Idloc = null, CompMac = null },
    new AddDesignation { ID = 208, SID = 105, RegDate = null, Designation = "Vaccinator", UId = null, Idloc = null, CompMac = null }
);
        }

    }

}
